CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "UploadStatus" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Strategy" text NOT NULL,
    CONSTRAINT "PK_UploadStatus" PRIMARY KEY ("Id")
);

CREATE TABLE "Uploads" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "FilePath" text NOT NULL,
    "StatusId" bigint NOT NULL,
    "Uuid" text NOT NULL,
    CONSTRAINT "PK_Uploads" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Uploads_UploadStatus_StatusId" FOREIGN KEY ("StatusId") REFERENCES "UploadStatus" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Uploads_StatusId" ON "Uploads" ("StatusId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251008031048_Migration_20251008_001040', '9.0.9');

COMMIT;

